# Generated by Django 4.1.5 on 2023-05-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contacts',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
    ]
