# Generated by Django 4.1.5 on 2023-05-27 20:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companytime_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
