version: "3.9"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: es01
    networks:
      - elastic
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    mem_limit: 1g
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kibana
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - es01  # Ensure Kibana starts after Elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://es01:9200  # Connect Kibana to Elasticsearch

volumes:
  elasticsearch_data:  # Define a named volume for Elasticsearch data persistence

networks:
  elastic:  # Create a custom Docker network for the services
